# 通用错误页面配置

# 404 错误
error_page 404 /404.html;

# 50x 错误
error_page 500 502 503 504 /50x.html;

# 错误页面 location
location = /404.html {
    internal;
    root /var/www/error;
}

location = /50x.html {
    internal;
    root /var/www/error;
}

# 403 错误
error_page 403 /403.html;
location = /403.html {
    internal;
    root /var/www/error;
}
